/* @pjs pauseOnBlur="true"; 
        preload= "data/Background3.png,
                  data/cheat game.png,
                  data/fink.png,
                  data/helper.png,
                  data/level2.png,
                  data/level3_1.png,
                  data/level4.png,
                  data/Lose.png,
                  data/paper.png,
                  data/pause.png,
                  data/rule.png,
                  data/rule2.png,
                  data/house.png,
                  data/student.png,
                  data/t.png,
                  data/TA.png,
                  data/Win.png,
                  data/you.png;
                  */
