/* @pjs pauseOnBlur="true"; 
        preload= "data/gameover.png,
                  data/gamewin.png,
                  data/goldfish.png,
                  data/goldfish2.png,
                  data/mau1.png,
                  data/mau2.png,
                  data/mauDead.png,
                  data/mauJump.png,
                  data/mauStand.png,
                  data/pause.png,
                  data/playbk.png,
                  data/Rope 100.png,
                  data/Rope 110.png,
                  data/Rope 150.png,
                  data/Rope 200.png,
                  data/Rope 270.png,
                  data/shiro.png,
                  data/shiro2.png,
                  data/startt.png;
                  */
